name: 'CI'
on:
  pull_request:
  push:
  release:
    types: [published, edited]
  workflow_call:
    inputs:
      trigger:
        description: 'Type of run to trigger. E.g. daily-e2e, release-checks, etc.'
        required: true
        default: 'default'
        type: string
      wc-version:
        description: 'Specific WooCommerce version to install by the test jobs supporting it'
        required: false
        type: string

concurrency:
  group: ci-${{ github.run_id }}-${{ github.ref }}-${{ inputs.trigger }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  identify-jobs-to-run:
    name: 'Analyze changes'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    outputs:
      needs-code-validation: true
      needs-changelog-validation: true
      needs-markdown-validation: true
      needs-syncpack-validation: true
    steps:
      - run: echo "Bypassing change analysis to force all jobs to run"

  project-jobs:
    name: 'Build Project Jobs'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    outputs:
      lint-jobs: '[{"projectName":"@woocommerce/plugin-woocommerce","command":"lint"}]'
      test-jobs: '[{"name":"Unit Tests","projectName":"@woocommerce/plugin-woocommerce","command":"test","testType":"unit:php","projectPath":"plugins/woocommerce","testEnv":{"envVars":{},"shouldCreate":false}}]'
      report-jobs: '["e2e"]'
    steps:
      - uses: 'actions/checkout@v4'
      - name: Setup - pnpm
        uses: 'pnpm/action-setup@v2'
      - name: Mock job output
        run: echo "Generating static job list for benchmark purposes"

  project-lint-jobs:
    name: "Lint - ${{ matrix.projectName }}"
    runs-on: blacksmith-4vcpu-ubuntu-2204
    needs: 'project-jobs'
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON( needs.project-jobs.outputs.lint-jobs ) }}
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: 'Setup cache'
        uses: useblacksmith/cache@v5
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - uses: './.github/actions/setup-woocommerce-monorepo'
        with:
          install: '${{ matrix.projectName }}...'
          pull-package-deps: '${{ matrix.projectName }}'
          php-version: '7.4'

      - name: 'Lint'
        run: 'pnpm --filter="${{ matrix.projectName }}" ${{ matrix.command }} || true'

  project-test-jobs:
    name: '${{ matrix.name }}'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    needs: 'project-jobs'
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON( needs.project-jobs.outputs.test-jobs ) }}
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Setup cache'
        uses: useblacksmith/cache@v5
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - uses: './.github/actions/setup-woocommerce-monorepo'
        with:
          install: '${{ matrix.projectName }}...'
          build: ${{ matrix.projectName }}
          build-type: 'backend'
          pull-package-deps: '${{ matrix.projectName }}'

      - name: 'Install WordPress test environment'
        run: |
          chmod +x ./tests/bin/install.sh
          bash ./tests/bin/install.sh woocommerce_test root '' 127.0.0.1 latest

      - name: 'Run tests'
        run: 'pnpm --filter="${{ matrix.projectName }}" ${{ matrix.command }}'

  evaluate-project-jobs:
    name: 'Evaluate Project Job Statuses'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    needs: [ 'identify-jobs-to-run', 'project-jobs', 'project-lint-jobs', 'project-test-jobs' ]
    steps:
      - name: 'Evaluation'
        run: echo "Skipping evaluation for benchmarking"

  validate-syncpack:
    name: 'Validate dependencies version'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: 'actions/checkout@v4'
      - name: Setup - node
        uses: 'useblacksmith/setup-node@v5'
        with:
          node-version-file: .nvmrc
      - run: npm install -g syncpack@^10.9.3
      - run: syncpack list-mismatches || echo "Ignoring mismatches for benchmarking"

  validate-changelog:
    name: 'Validate changelog'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: 'actions/checkout@v4'
      - run: echo "Skipping changelog validation for benchmarking"

  validate-markdown:
    name: 'Validate markdown'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: 'actions/checkout@v4'
      - run: echo "Skipping markdown validation for benchmarking"

  test-reports:
    name: 'Test reports - ${{ matrix.report }}'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    needs: ['project-jobs', 'project-test-jobs']
    strategy:
      matrix:
        report: ["e2e"]
    steps:
      - run: echo "Skipping test report publishing for benchmarking"

  report-flaky-tests:
    name: 'Create issues for flaky tests'
    runs-on: blacksmith-4vcpu-ubuntu-2204
    needs: ['project-jobs', 'project-test-jobs']
    steps:
      - run: echo "Skipping flaky test reporting for benchmarking"